### ISSUE TITLE
Invalid URI Error

### ISSUE THREAD

**Issue by BrendanThompson** [devondragon/jira-omnifocus#17]
When running, I get the following:

```
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split': bad URI(is not URI?): https://example.atlassian.net/rest/api/2/issue/KEY-123 (URI::InvalidURIError)



                    We are getting an alert about file server space in production, archive to s3 and then glacier. reduce the size of some drives to save space.
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/uri/common.rb:713:in `URI'
	from ./jiraomnifocus.rb:205:in `block in mark_resolved_jira_tickets_as_complete_in_omnifocus'
	from ./jiraomnifocus.rb:199:in `each'
	from ./jiraomnifocus.rb:199:in `find'
	from ./jiraomnifocus.rb:199:in `each'
	from ./jiraomnifocus.rb:199:in `mark_resolved_jira_tickets_as_complete_in_omnifocus'
	from ./jiraomnifocus.rb:250:in `main'
	from ./jiraomnifocus.rb:254:in `<main>'
```

**Comment by BrendanThompson** [comment]
This seems to be caused when there is more than just the Jira URI in the notes field in omnifocus. I have updated my fork to fix this issue.

**Comment by devondragon** [comment]
Cool!  I don't see the change in your fork yet?  Can you submit a PR with the fix?
