### ISSUE TITLE
SSL Connection issue on OS X

### ISSUE THREAD

**Issue by devondragon** [devondragon/jira-omnifocus#33]
Due to OS X default OpenSSL libraries being older (OpenSSL 0.9.8zh), when using Ruby (Net::HTTP) to connect to a secure modern TLS server, he following error happens:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert internal error (OpenSSL::SSL::SSLError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from bin/jiraomnifocus.rb:97:in `get_issues'
	from bin/jiraomnifocus.rb:251:in `add_jira_tickets_to_omnifocus'
	from bin/jiraomnifocus.rb:421:in `main'
	from bin/jiraomnifocus.rb:432:in `<main>'

There are a TON of online articles about this issue, but no easy solution I have found.

**Comment by devondragon** [comment]
Still haven't found a solution:(. I can't get TLS1.2 support to work.

**Comment by devondragon** [comment]
Is anyone having this problem?  Any workarounds or solutions?

**Comment by devondragon** [comment]
Installed Ruby 2.1.2, and set that as my global version using rbenv.  Updated to the post-PR merge https://github.com/devondragon/jira-omnifocus/pull/39. and ran bundle update.  Now things work great!!
